project_id = "gfirdlgucifvpffovlcs"

[functions.scrape-cars]
verify_jwt = false

[functions.download-listing-images]
verify_jwt = false

[functions.save-listing-image]
verify_jwt = false

[functions.publish-to-social]
verify_jwt = false

[functions.remove-watermark]
verify_jwt = false